<?xml version="1.0"?>
<!--
Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying 
documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, 
and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject 
to the following:

The copyright notices in the Software and this entire statement, including the above license grant, the original location it was 
downloaded from, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, 
and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object
code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. THE SOFTWARE MAY CONTAIN BUGS, ERRORS AND OTHER
PROBLEMS THAT COULD CAUSE SYSTEM FAILURES AND THE USE OF SUCH SOFTWARE IS ENTIRELY AT THE USER'S RISK. IN NO EVENT SHALL THE COPYRIGHT
HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

************************************************************************************************************************************
This file defines new UI elements that all workspaces will contain
************************************************************************************************************************************
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:frmwrk="Corel Framework Data">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>

	<!-- Use these elements for the framework to move the container from the app config file to the user config file -->
	<!-- Since these elements use the frmwrk name space, they will not be executed when the XSLT is applied to the user config file -->
	<frmwrk:uiconfig>
		<!-- The Application Info should always be the topmost frmwrk element -->
		<frmwrk:applicationInfo userConfiguration="true" />
	</frmwrk:uiconfig>

	<!-- Copy everything -->
	<xsl:template match="node()|@*">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>
		</xsl:copy>
	</xsl:template>

	<xsl:template match="uiConfig/items">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>


			<!--Creates a item to add a Warpper, responsible to initialize the DataSource to be consumimed in menu item above -->
			<itemData guid="9d86b3ac-5c08-4c95-9c22-288173525877"
					  type="wpfhost"
					  hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.ControlUI"
					  enable="true"/>

			<!-- Run Command Docker Button onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=RunCommandDocker)"-->
			<itemData guid="7acb54e6-084e-494f-ad31-2718f34ddad2"
					 check="*Docker('5087687d-337d-4d0e-acaf-c0b1df967757')"
					  icon="guid://7acb54e6-084e-494f-ad31-2718f34ddad2"
					  type="checkButton"  enable="true"/>



			<!-- DrawUI Explorer Button-->
			<itemData guid="942df043-e3e2-4d0e-83ee-a456557ac093"
					  onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=RunDrawUIExplorer)"
					  icon="guid://942df043-e3e2-4d0e-83ee-a456557ac093"
					  type="button"  enable="true"/>

			<!-- Shortcuts Button onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=RunShortcutsDocker)"-->
			<itemData guid="b0bc23ba-086b-46d1-ae04-ee36aa9003a4"
					  check="*Docker('512194ae-a540-4979-8991-bcadded6726e')"
					  icon="guid://b0bc23ba-086b-46d1-ae04-ee36aa9003a4"
					  type="checkButton"  enable="true"/>

			<!--Run command docker-->
			<itemData guid="2ee3372b-f6b5-47fe-aa81-4ecd2c4771e2"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.RunCommandDocker.DockerUI"
					enable="true"/>

			<!--Shortcuts docker-->
			<itemData guid="c934c5dc-882b-476a-a634-b1d9ab7c81f1"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.ControlsShorcutsCDRAddon.DockerUI"
					enable="true"/>

			<!--GMS Dragger-->
			<itemData guid="3b3f72b8-0129-4316-b8a3-40e4758ba9bc"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.GMSDragger.Dragger"
					enable="true"/>

			<!--Reload GMS-->
			<itemData guid="9b07d7af-da14-4cd8-9db9-7da214ee1d4a"
					  onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=ReloadNRestoreUserGMS)"
					  icon="guid://9b07d7af-da14-4cd8-9db9-7da214ee1d4a"
					  dropDownRef='b0a4b2ff-7bf5-47c3-a92a-16e2a4520746'
					  type="dropDownDlgBtn"  enable="true" arrowStyle='down'/>
			
			<!--PopUp GMS-->
			<itemData guid="b0a4b2ff-7bf5-47c3-a92a-16e2a4520746"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.GMSDragger.GMSLoader"
					enable="true"/>
			
			<!-- Unload and Delete GMS-->
			<itemData guid="571db7b2-8cae-4b99-b241-a56ecd61f90e"
					  onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=UnloadNDeleteUserGMS)"
					  icon="guid://571db7b2-8cae-4b99-b241-a56ecd61f90e"
					  type="button"  enable="true"/>
			
			<!--CQL Runner-->
			<!--<itemData guid="08bdac37-d2b9-42ad-a498-5335df9783c7"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.CQLRunner.CQLRunner"
					enable="true"/>-->	
			
			<!--DropdownButton CqL-->
			<itemData guid='51b24cfb-b8df-411f-886c-4c5520e931a4' type='dropDownDlgBtn' arrowStyle='down'
					  caption='*Bind(DataSource=Bonus630DevToolsBarDS;Path=CQLCaption)'
					  toolTip='*Bind(DataSource=Bonus630DevToolsBarDS;Path=CQLTooltip)'
					  dropDownRef='8a8ca94c-cc61-4f14-b24d-cbd447d2fd56'
					  icon="guid://51b24cfb-b8df-411f-886c-4c5520e931a4"
					  length='100' enable='true'/>

			<!--PopUp CQL-->
			<itemData guid="8a8ca94c-cc61-4f14-b24d-cbd447d2fd56"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.CQLRunner.CQLRunner"
					enable="true"/>
			
					
			<!--cql reference guid-->
			<itemData guid="d61f1ede-79aa-4255-8f96-307e6f63c204"
			  onInvoke="*Bind(DataSource=Bonus630DevToolsBarDS;Path=OpenCQLGuide)"
			  icon="guid://d61f1ede-79aa-4255-8f96-307e6f63c204"
			  type="button"  enable="true"/>

			<!--DropdownButton Folders-->
			<itemData guid='680d03b3-2da0-4314-bc79-fa6b26471e22' type='dropDownDlgBtn' arrowStyle='down'
					  caption='*Bind(DataSource=Bonus630DevToolsBarDS;Path=FoldersCaption)'
					  toolTip='*Bind(DataSource=Bonus630DevToolsBarDS;Path=FoldersTooltip)'
					  dropDownRef='d13b83a4-3ef6-4ead-b95d-44d467dc47f5'
					  icon="guid://680d03b3-2da0-4314-bc79-fa6b26471e22"
					  length='100' enable='true'/>

			<!--PopUp Folders-->
			<itemData guid="d13b83a4-3ef6-4ead-b95d-44d467dc47f5"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.Folders.Folders"
					enable="true"/>
			
			
			
			
			<!--Recent Files-->
			<itemData guid="7d15e9c7-2431-4841-a5aa-9eaa5b581230"
					type="wpfhost"
					hostedType="Addons\Bonus630DevToolsBar\Bonus630DevToolsBar.dll,br.com.Bonus630DevToolsBar.RecentFiles.RecentFilesView"
					enable="true"/>




		</xsl:copy>
	</xsl:template>

	<!--Create a custom command bar below standard bar-->
	<xsl:template match="uiConfig/commandBars">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>

			<commandBarData guid="48024933-d18b-4e0a-9b59-96a6b99a418e"
							nonLocalizableName="Bonus630 Dev Tools"
							userCaption="Bonus630 Dev Tools"
							locked="true"
							type="toolbar"
							dock="fill">
				
					<toolbar dock="fill">
						<!--Data Source-->
						<item  guidRef="9d86b3ac-5c08-4c95-9c22-288173525877" dock="top"/>
						<!--Run Command Docker Button-->
						<item  guidRef="7acb54e6-084e-494f-ad31-2718f34ddad2" dock="top"/>
						<!--Separator-->
						<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400" />
						<!--DrawUI Explorer Button-->
						<item  guidRef="942df043-e3e2-4d0e-83ee-a456557ac093" />
						<!--Shortcut Button-->
						<item  guidRef="b0bc23ba-086b-46d1-ae04-ee36aa9003a4" dock="top"/>
						<!--Separator-->
						<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400" />
						<!--GMS Dragger-->
						<item  guidRef="3b3f72b8-0129-4316-b8a3-40e4758ba9bc" dock="top"/>
						<!--Macro Manager-->
						<item guidRef="13d17830-0ba8-4f71-85e0-6df0a1051eee" dock="top" />
						<!--Reload Gms -->
						<item  guidRef="9b07d7af-da14-4cd8-9db9-7da214ee1d4a" dock="top"/>
						<!--Unload and Delete GMS -->
						<item  guidRef="571db7b2-8cae-4b99-b241-a56ecd61f90e" dock="top"/>
						<!--Separator-->
						<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400" />
					
						<!--CqlRunner -->
						<item  guidRef="51b24cfb-b8df-411f-886c-4c5520e931a4" />	
						<!--CqlHelp -->
						<item  guidRef="d61f1ede-79aa-4255-8f96-307e6f63c204" />	
						<!--Separator-->
						<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400" />
						<!--Folders-->
						<item guidRef="680d03b3-2da0-4314-bc79-fa6b26471e22" />
						<!--Separator-->
						<item guidRef="266435b4-6e53-460f-9fa7-f45be187d400" />
						<!--Recent Files -->
						<item  guidRef="7d15e9c7-2431-4841-a5aa-9eaa5b581230" dock="fill"/>
						<!--<item  guidRef="118bad9e-cab3-4810-883e-843626f798ae" dock="top"/>-->

					</toolbar>
				
			</commandBarData>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<xsl:template match="uiConfig/containers/container[@guid='bee85f91-3ad9-dc8d-48b5-d2a87c8b2109']/container[@guid='Framework_MainFrame-layout']/dockHost[@guid='894bf987-2ec1-8f83-41d8-68f6797d0db4']/toolbar[@guidRef='c2b44f69-6dec-444e-a37e-5dbf7ff43dae']">
		<xsl:copy-of select="."/>

		<toolbar dock="fill" guidRef="48024933-d18b-4e0a-9b59-96a6b99a418e" />

	</xsl:template>
	<xsl:template match="uiConfig/dockers">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>

			<!-- Define RunCommandDocker -->
			<dockerData guid="5087687d-337d-4d0e-acaf-c0b1df967757"
						userCaption="Run Command"
						wantReturn="true"
						icon="guid://7acb54e6-084e-494f-ad31-2718f34ddad2"
						focusStyle="noThrow">
				<container>
					<!-- add the webpage control to the docker -->
					<item dock="fill" margin="0,0,0,0" guidRef="2ee3372b-f6b5-47fe-aa81-4ecd2c4771e2"/>
				</container>
			</dockerData>

			<!-- Define ShortcutsDocker -->
			<dockerData guid="512194ae-a540-4979-8991-bcadded6726e"
						userCaption="Shortcuts"
						wantReturn="true"
						icon="guid://b0bc23ba-086b-46d1-ae04-ee36aa9003a4"
						focusStyle="noThrow">
				<container>
					<!-- add the webpage control to the docker -->
					<item dock="fill" margin="0,0,0,0" guidRef="c934c5dc-882b-476a-a634-b1d9ab7c81f1"/>
				</container>
			</dockerData>
		</xsl:copy>
	</xsl:template>
	
	<xsl:template match="uiConfig/dialogs">
		<xsl:copy>
			<xsl:apply-templates select="node()|@*"/>
			<!-- Pop up CQL Runner-->
			<dialog guid="9b6ec438-14c9-44e2-92c3-c28411f093af"
						   popUp="true">

				<item  guidRef="8a8ca94c-cc61-4f14-b24d-cbd447d2fd56" dock="fill"/>

			</dialog>
			<!-- Pop up Folder-->
			<dialog guid="b83ecdef-7b82-46ee-bef3-d874902e031a"
						   popUp="true">

				<item  guidRef="d13b83a4-3ef6-4ead-b95d-44d467dc47f5" dock="fill"/>

			</dialog>
			<!-- Pop up GMS Load-->
			<dialog guid="acdc8c23-25cb-49a7-9346-0a6b69bbf5c9"
						   popUp="true">

				<item  guidRef="b0a4b2ff-7bf5-47c3-a92a-16e2a4520746" dock="fill"/>

			</dialog>

		</xsl:copy>
	</xsl:template>

</xsl:stylesheet>
